name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        # This action uses the secrets you've set up in your repository settings.
        # It's the most secure way to handle credentials.
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        # This command builds the image from your Dockerfile and tags it with your Docker Hub username.
        run: docker build -t kamalkumar25/nodejs-demo-app:latest .

      - name: Push Docker image
        # This command pushes the tagged image to your Docker Hub repository.
        run: docker push kamalkumar25/nodejs-demo-app:latest
